<!-- 3 col layout -->
<div class="container-fluid">
<!-- {{ page_tag() }} -->
    <div class="row">
	<div class="content_left col bottom_left">
	{{ content_next_left() }}  
	</div>
	<div class="content_main col-5 bottom_main">
	{{ content_next_main() }}                  

	</div>
	<div class="content_right col bottom_right">
	{{ content_next_right() }}                                  
	</div>
    </div>
</div>
